# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 799a3510e0c140796238e191b6bd6f79e9691fd71e3fdf7fb7cbb4e0d110b5403797f12a1510d1c5b7aea7d7053ed1cc6a8bfdd8d39f84ca598cae3f38dcb7a5

test:
  secret_key_base: b21346b07037b6b5b0a60de7bad29b47ac4292e2220a0015ffbc70eed1e34832b2b9cdc3e4516cb9f42f8ca3c0c77a8002b6dcce3f814c2d56ef1ba899fca67b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
